import "./globals.css";
import Header from "@/components/templates/Header";
import Chatbot from "@/components/chatbot";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const userInfo = {
    firstName: "John",
    lastName: "Doe",
  };

  return (
    <html lang="en">
      <body>
        <Header info={userInfo} />
        {children}
        <Chatbot />
      </body>
    </html>
  );
}
